### ISSUE TITLE
not correct proxies menu

### ISSUE THREAD

**Issue by legiz-ru** [snakem982/Pandora-Box#38]
1. dont work proxy-group with hidden: true 

2. not correct sorting:

Config:

<details>
  <summary>yaml↓ </summary>
  
```yaml
proxy-groups:
  - name: 🌍 VPN
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png
    type: select
    proxies:
      - ⚡️ Fastest
      - 📶 First Available
      - 🔗 Chain 🇷🇺➡️🌍
      # LEAVE THIS LINE!
  - name: 🔗 EndChain # Выбор конечного сервера для цепочки из РФ на другие ноды
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - ⚡️ Fastest
      - 📶 First Available
      # LEAVE THIS LINE!
  - name: ▶️ YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies:
      - 🌍 VPN
      # LEAVE THIS LINE!
  - name: 💬 Discord
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    type: select
    proxies:
      - 🌍 VPN
      # LEAVE THIS LINE!
  - name: 💌 Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies:
      - DIRECT
      - 🌍 VPN
      # LEAVE THIS LINE!
  - name: ☁️ Cloudflare
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: select
    proxies:
      - DIRECT
      - 🌍 VPN
      # LEAVE THIS LINE!
  - name: ⚡️ Fastest
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    tolerance: 150
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      # LEAVE THIS LINE!
  - name: 📶 First Available
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Download.png
    type: fallback
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      # LEAVE THIS LINE!
  - name: 🔗 Chain 🇷🇺➡️🌍
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Russia.png
    hidden: true
    type: relay
    remnawave: # Кастомное поле используемое только в Remnawave (отключает добавление всех прокси в данную секцию, кроме указанных вручную)
      include-proxies: false
    proxies:
    - 🇷🇺 Russia WS # Здесь имя хоста вашей ноды в России
    - 🔗 EndChain
```

</details>

Pandora:

<details>
  <summary>screenshot ↓ </summary>
  
![Image](https://github.com/user-attachments/assets/8d16f1ec-eaa2-4003-83d3-86f07dcd9ad8)

</details>

FlClash:

<details>
  <summary>screenshot ↓ </summary>
  
![Image](https://github.com/user-attachments/assets/7e61e96d-72f2-4e26-903f-bb41c150fd4f)

</details>
