### ISSUE TITLE
[bug] not correct parsing sb+vless+ws+mux

### ISSUE THREAD

**Issue by legiz-ru** [snakem982/Pandora-Box#47]
sing-box.json vless ws with mux:

outbound import:
```json
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "vless",
      "tag": "proxy",
      "server": "example.com",
      "server_port": 443,
      "uuid": "dd******c5e",
      "tls": {
        "enabled": true,
        "server_name": "example.com",
        "utls": {
          "enabled": true,
          "fingerprint": "randomized"
        }
      },
      "multiplex": {
        "enabled": true,
        "padding": true
      },
      "transport": {
        "type": "ws",
        "path": "/wspath"
      }
    }
  ],
```

pandora-box import:
```yaml
proxies:
    - client-fingerprint: randomized
      flow: ""
      name: proxy
      network: ws
      port: 443
      server: example.com
      servername: example.com
      skip-cert-verify: true
      tls: true
      type: vless
      uuid: dd******c5e
      ws-opts:
        path: /wspath
      xudp: true
```

correct import:
```yaml
proxies:
- name: "VLESS-CLIENT"
  type: vless
  server: example.com
  port: 443
  uuid: dd******c5e
  network: ws
  tls: true
  servername: example.com
  client-fingerprint: randomized
  ws-opts:
    path: /wspath
  smux:
    enabled: true
    padding: true
  udp: true
  tcp: true
  skip-cert-verify: false
```

**Comment by snakem982** [comment]
The code does not parse the multiplex field, it will be added in the next version

**Comment by snakem982** [comment]
Sing-box analysis is not yet complete, use with caution

**Comment by legiz-ru** [comment]
> Sing-box analysis is not yet complete, use with caution

Is it possible to fix this in the future?

**Comment by snakem982** [comment]
Because sing-box is frequently modified, I don't remember which version of the document was used. Most of it has been completed, but some fields may not be parsed. I can only modify it if us find a bug.

**Comment by legiz-ru** [comment]
@snakem982 pls add udp: true to 

current alpha:
```yaml
proxies:
    - client-fingerprint: randomized
      flow: ""
      name: proxy
      network: ws
      port: 443
      server: example.com
      servername: example.com
      skip-cert-verify: true
      smux:
        enabled: true
        padding: true
      tls: true
      type: vless
      uuid: dd******c5e
      ws-opts:
        path: /wspath
      xudp: true

```
